> *The creation of the lessons in this unit relied heavily on the existing lessons created by Mrs. FitzZaland as well as the [lecture series](https://github.com/milaan9/10_Python_Pandas_Module) produced by Dr. Milaan Parmar. Additionally, these lessons have largely been modelled off of the book [Think Python](https://open.umn.edu/opentextbooks/textbooks/43) by Allen Downey.*

# Pandas

This Pandas lesson will help you learn all the Pandas basics.

If it would be beneficial for your learning, feel free to **take a look at [this 20 minute video](https://www.youtube.com/watch?v=zN2Hua6oII0)** that goes through most of the content covered in this lesson.

<div class="alert alert-info"><h4>Tasks</h4><p>Alert boxes like this will provide you with tasks that you must do while going through this lesson.</p></div>

**[Pandas](https://pandas.pydata.org/)** provides a fast, flexible, handy, and expressive data structure tool that is designed to make working with 'relational' or 'labeled' data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real world complex data analysis in Python.

> Pandas is kind of like a simple version of Excel for Python.

Pandas is well suited for many different kinds of data including:

* Tabular data with heterogeneously-typed columns, as in an SQL table or Excel spreadsheet
* Time series data
* Arbitrary matrix data with row and column labels
* Any other form of observational / statistical data sets

# Pandas' DataFrame

In this lesson, you will learn about Pandas' DataFrame. The lesson covers the basics of DataFrames: its attributes, functions, and how to use DataFrames for data analysis.

> The DataFrame is the most widely used data structure in Pandas. You can imagine it as a table in a database or a spreadsheet.

## What is a DataFrame in Pandas

A DataFrame is a tabular (rows and columns) representation of data. It is a two-dimensional data structure that allows for the data to be in different types (unlike numpy arrays which only allow for a single data type).

A Dataframe is a size-mutable structure, which means that data can be added or deleted from it; unlike a data series, which does not allow operations that change its size.

<div>
<img src="images/dataframe.png" width="600"/>
</div>

## DataFrame creation

Data is available in various forms and types like CSV, SQL table, JSON, or Python structures like list, dictionaries, etc. We need to convert all such different data formats into a DataFrame so that we can use pandas libraries to analyze the data efficiently.

To create a DataFrame, we can use either the DataFrame constructor or pandas built-in functions.

### DataFrame constructor

```python
pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)
```

#### Parameters:

- **`data`**: This can either be a **`dict`**, **`list`**, **`set`**, **`ndarray`**, **`iterable`**, or a DataFrame. If the input is not provided, then it creates an empty DataFrame. The resultant column order follows the order of the inserted data.

- **`index`**: (Optional) It takes the list of row index for the DataFrame. The default value is a range of integers 0, 1,…n.


- **`columns`** : (Optional) It takes the list of column headers for the DataFrame. The default value is a range of integers 0, 1,…n.


- **`dtype`**: (Optional) By default, It infers the data type from the data, but this option applies any specific data type to the whole DataFrame.

## Dictionaries

One way to create a DataFrame is to organize your data into a dictionary, which is actually something we haven't looked at yet!

### What is a Dictionary?

A dictionary in Python is an unordered collection of items. It consists of key-value pairs where each key must be unique. Dictionaries are defined using curly braces `{}` and can be used to store and retrieve data efficiently.

<div>
<img src="images/dictionary.png" width="600"/>
</div>

* **Dictionaries are mutable** i.e., the values can be updated.

* Keys must be unique and are immutable; i.e. the keys can't be changed

### Creating a Dictionary

Let's start by creating a simple dictionary:

In [1]:
# Creating a dictionary
my_dict = {'name': 'Taylor', 'age': 25, 'city': 'New York'}
print(my_dict)

{'name': 'Taylor', 'age': 25, 'city': 'New York'}


### Accessing Values

You can access the values in a dictionary using the keys:

In [2]:
print("Name:", my_dict['name'])
print("Age:", my_dict['age'])
print("City:", my_dict['city'])

Name: Taylor
Age: 25
City: New York


<div class="alert alert-info"><h4>1.</h4><p>Create a new notebook and name it Lesson9_Tasks.</p></div>

<div class="alert alert-info"><h4>2.</h4><p>In your notebook, define a dictionary using the following code.</p></div>

```python
my_dict = {'name': 'Taylor', 'age': 25, 'city': 'New York'}
```

### Adding New Key-Value Pairs

You can add new key-value pairs to the dictionary:

<div class="alert alert-info"><h4>3.</h4><p>Try adding the following key/value pair to you dictionary:</p></div>

```python
my_dict['occupation'] = 'Engineer'
print("Updated Dictionary:", my_dict)
```

### Dictionary Methods


`keys()`: Returns a list of all keys in the dictionary.

<div class="alert alert-info"><h4>4.</h4><p>Print the keys in your dictionary:</p></div>

```python
# Using keys()
keys = my_dict.keys()
print("Keys:", keys)
```

`values()`: Returns a list of all values in the dictionary.

<div class="alert alert-info"><h4>5.</h4><p>Print the values in your dictionary:</p></div>

```python
# Using values()
values = my_dict.values()
print("Values:", values)
```

`items()`: Returns a list of key-value pairs as tuples.

<div class="alert alert-info"><h4>6.</h4><p>Print the key-value pairs in your dictionary:</p></div>

```python
# Using items()
items = my_dict.items()
print("Items:", items)
```

### Creating a Dataframe from a dictionary

Ok now back to Pandas!

When we have data in a **`dict`** (or any default data structures in Python) we can convert it into a DataFrame using the DataFrame constructor **`pd.DataFrame(dict)`**. 

It creates a DataFrame where the **`dict`** keys will be column labels, and the **`dict`** values will be the columns’ data. 

In [3]:
# Example of creating a dictionary
student_dict = {'Name':['Joe','Nat'], 'Age':[20,21], 'Marks':[85.10, 77.80]}
student_dict

{'Name': ['Joe', 'Nat'], 'Age': [20, 21], 'Marks': [85.1, 77.8]}

In the example above, **'Name'**, **'Age'** and **'Marks'** are the keys in the **`dict`**. 

When you convert the dictionary into a DataFrame, these keys will become the column labels of the DataFrame:

In [4]:
import pandas as pd

# Defining your dictionary object
student_dict = {'Name': ['Joe', 'Nat'], 'Age': [20, 21], 'Marks': [85.10, 77.80]}
print(student_dict)

# Create DataFrame from dict
student_df = pd.DataFrame(student_dict)
print(student_df)

{'Name': ['Joe', 'Nat'], 'Age': [20, 21], 'Marks': [85.1, 77.8]}
  Name  Age  Marks
0  Joe   20   85.1
1  Nat   21   77.8


> Note that - similar to what we did with numpy - here we have imported pandas under the name `pd`

One nice feature of working in a notebook like this, is that the notebook has a built-in pretty display format for Pandas' DataFrames. You can use this display by simply writing the DataFrame object without the print statement as seen below. (Note that this has to be the last line your code cell to display).

(Also note that Deepnote's display is slightly different than the native JupyterLab display.)

In [5]:
student_df

Name  Age  Marks
0  Joe   20   85.1
1  Nat   21   77.8

<div class="alert alert-info"><h4>7.</h4><p>In a new code cell, convert the following dictionary into a dataframe:</p></div>

```python
{'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
```

You can also provide labels for each row using the index parameter of the DataFrame or assigning this attribute after you have already defined your dataframe.

<div class="alert alert-info"><h4>8.</h4><p>Add row labels to your DataFrame:</p></div>

```python
# For example
df.index=['a','b','c','d','e']
```

where `df` is the variable name for your own DataFrame.

<div class="alert alert-info"><h4>9.</h4><p>Display your dataframe in your notebook to see what it looks like.</p></div>

### Indexing

With Pandas, we can use labeled indexing. 

We can select subsets of the data by column, row, or both. 

Pass in a single column label or a list of labels to select subsets of the original **`DataFrame`**.

<div class="alert alert-info"><h4>10.</h4><p>In separate code cells, try displaying each of the following types of indexing methods into your DataFrame:</p></div>

```python
# Single column (reduces to a Series)
df['X']
```

(Remember to create a new code cell each time).

```python
# Multiple columns (creates a subset DataFrame)
cols = ['X', 'Z']
df[cols]
```

```python
# For row-wise selection, use the special .loc accessor
df.loc[['a', 'c']]
```

```python
# You can use ranges to select rows or columns.
df.loc['a':'c']
```

Notice that the slice is *inclusive* on both sides,  unlike your typical slicing of a list. Sometimes, you'd rather slice by *position* instead of label. **`.iloc`** has you covered:

```python
# Use row positions
df.iloc[[0, 1]]
```

```python
# Use row position slicing
df.iloc[:2]
```

This follows the usual python slicing rules: closed on the left, open on the right.

As I mentioned, you can slice both rows and columns. Use **`.loc`** for label or **`.iloc`** for position indexing:

```python
df.loc['a', 'X']
```

Pandas will reduce dimensions when possible. Select a single column and you get back `Series` (see below). Select a single row and single column, you get a scalar.

You can get pretty fancy:

```python
df.loc['a':'b', ['X', 'Z']]
```

#### Summary

- Use **`[]`** for selecting columns
- Use **`.loc[row_lables, column_labels]`** for label-based indexing
- Use **`.iloc[row_positions, column_positions]`** for positional index

I've left out boolean and hierarchical indexing, which we'll see later.

## Series

You've already seen some **Series** up above. 

> A Series is the 1-dimensional analog of the DataFrame. 

Each column in a **DataFrame** is in some sense a **Series**. You can select a **Series** from a DataFrame in a few ways:

In [6]:
# Another example:
import pandas as pd

# We pass a dict of {column name: column values} for the data
# and also provide labels for each row in this case
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]},
                 index=['a','b','c','d','e']);
df

X   Y   Z
a  78  84  86
b  85  94  97
c  96  89  96
d  80  83  72
e  86  86  83

In [7]:
# indexing using the column name
df['Y']

a    84
b    94
c    89
d    83
e    86
Name: Y, dtype: int64

In [8]:
# .loc with column name
df.loc[:, 'Y']

a    84
b    94
c    89
d    83
e    86
Name: Y, dtype: int64

In [9]:
# using `.` attribute to lookup the column
df.Y

a    84
b    94
c    89
d    83
e    86
Name: Y, dtype: int64

You can also add a new column (or series) to your DataFrame:

In [10]:
df['W'] = ['h', 'i', 'j', 'k', 'l']
df

X   Y   Z  W
a  78  84  86  h
b  85  94  97  i
c  96  89  96  j
d  80  83  72  k
e  86  86  83  l

You can access the indices and columns of a **DataFrame** or **Series** with the **`.index`** and **`.columns`** attributes.

In [11]:
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [12]:
df.columns

Index(['X', 'Y', 'Z', 'W'], dtype='object')

### Dataframe from CSV

In the field of Data Science, **[CSV](https://en.wikipedia.org/wiki/Comma-separated_values)** files are used to store large datasets. To efficiently analyze such datasets, we can convert them into a pandas DataFrame.

To create a DataFrame from a CSV file, we can use the **`pd.read_csv('file_name')`** function that takes the file name as an input and returns a DataFrame as output.

**Example 1:** 

Let’s read the **[stockprice_data.csv](https://github.com/milaan9/10_Python_Pandas_Module/blob/main/stockprice_data.csv)** file into a DataFrame and then convert it into a Series:

<div>
<img src="images/csvfile1.png" width="300" />
</div>

In [13]:
import pandas as pd

# Load all of the data into a DataFrame
data = pd.read_csv("stockprice_data.csv")
data

Date  Closing price    Return
0    1/1/2020            100  0.010000
1    2/1/2020            120  0.200000
2    3/1/2020            130  0.083333
3    4/1/2020             98 -0.246154
4    5/1/2020             50 -0.489796
5    6/1/2020            102  1.040000
6    7/1/2020            104  0.019608
7    8/1/2020            150  0.442308
8    9/1/2020            160  0.066667
9   10/1/2020            109 -0.318750
10  11/1/2020             95 -0.128440

In [14]:
# Use indexing to select the 3rd column (index=2)
# and assign this to a new variable
data1 = data.iloc[:,2]
data1

0     0.010000
1     0.200000
2     0.083333
3    -0.246154
4    -0.489796
5     1.040000
6     0.019608
7     0.442308
8     0.066667
9    -0.318750
10   -0.128440
Name: Return, dtype: float64

In [15]:
# Use indexing to select the 3rd row
data2 = data.iloc[2,:]
data2

Date             3/1/2020
Closing price         130
Return           0.083333
Name: 2, dtype: object

### Get the statistics of DataFrame

**`DataFrame.describe()`** is a function that provides statistics of the data in DataFrame. It only applies to the columns that contain numerical values.

These statistics include:

1. **count**: Total number of non-null values in the column
2. **mean**: an average of numbers
3. **std**: a standard deviation value
4. **min**: minimum value
5. **25%**: 25th percentile
6. **50%**: 50th percentile
7. **75%**: 75th percentile
8. **max**: maximum value

>**Note:** Output of **`DataFrame.describe()`** function varies depending on the input DataFrame.

<div class="alert alert-info"><h4>11.</h4><p>In new code cell, use the following dictionary to create a new DataFrame:</p></div>

```python
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 
                'Age': [20, 21, 19], 
                'Marks': [85.10, 77.80, 91.54]}
```

<div class="alert alert-info"><h4>12.</h4><p>Use the .describe() function our your dataframe.</p></div>

For example, if your DataFrame is called `df`, you can call

```python
df.describe()
```

## DataFrame Attributes

The DataFrame has many built-in attributes. Attributes do not modify the underlying data, but they can be used to access details regarding the DataFrame.

Here are some commonly used attributes of the DataFrame:

| Attribute | Description |
|:---- |:---- |
| **`DataFrame.index`**   | **It gives the Range of the row index** | 
| **`DataFrame.columns`** | **It gives a list of column labels** |
| **`DataFrame.dtypes`**  | **It gives column names and their data type** | 
| **`DataFrame.values`**  | **It gives all the rows in DataFrame** |
| **`DataFrame.empty`**   | **It is used to check if the DataFrame is empty** | 
| **`DataFrame.size`**    | **It gives a total number of values in DataFrame** |
| **`DataFrame.shape`**   | **It a number of rows and columns in DataFrame** | 

<div class="alert alert-info"><h4>13.</h4><p>Try out the above attributes on your DataFrame.</p></div>


## DataFrame selection 

It can be helpful to grab particular subsets of your DataFrame.

The following are some functions that help in selecting subsets of your DataFrame:

| Attribute | Description |
|:---- |:---- |
| **`DataFrame.head(n)`**  | **Used to select the first ‘n’ rows in DataFrame.** | 
| **`DataFrame.tail(n)`**  | **Used to select the last ‘n’ rows in DataFrame.** | 
| **`DataFrame.at`**       | **Used to get and set the particular value of DataFrame using row and column labels.** | 
| **`DataFrame.iat`**      | **Used to get and set the particular value of DataFrame using row and column index positions.** | 
| **`DataFrame.get(key)`** | **Used to get the value of a key in DataFrame where Key is the column name.** | 
| **`DataFrame.loc()`**    | **Used to select a group of data based on the row and column labels. It is used for slicing and filtering of the DataFrame.** | 
| **`DataFrame.iloc()`**   | **Used to select a group of data based on the row and column index position. Use it for slicing and filtering the DataFrame.** | 

<div class="alert alert-info"><h4>14.</h4><p>Try out the .head() and .tail() functions on your DataFrame.</p></div>


## DataFrame modification

A DataFrame is similar to an excel sheet or a database table where it is often necessary to insert new data or **[drop columns]()** and rows if they are not needed.

In this section, we discuss the data manipulation functions of the DataFrame.

### Insert columns

Sometimes it is required to add a new column in the DataFrame. **`DataFrame.insert()`** function is used to insert a new column in DataFrame at the specified position.

In the below example, we insert a new column **'Class'** as a third new column in the DataFrame with default value ‘**A**’ using the syntax:

```python
df.insert(loc = col_position, column = new_col_name, value = default_value)
```

In [16]:
# Example:

import pandas as pd

# Create DataFrame from dict
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}
student_df = pd.DataFrame(student_dict)
print(student_df)

# insert new column in dataframe and display
student_df.insert(loc=2, column="Grade", value=['B', 'B', 'A'])
print("Updated dataframe:\n", student_df)

    Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54
Updated dataframe:
     Name  Age Grade  Marks
0    Joe   20     B  85.10
1    Nat   21     B  77.80
2  Harry   19     A  91.54


### Apply condition

We may need to update the values in the DataFrame based on some condition. **`DataFrame.where()`** function is used to replace the value of DataFrame, where the condition is **`False`**.

**Syntax of the condition:**
```python
where(filter, other=new_value)
```

It applies the filter condition on all the rows in the DataFrame, as follows:

* If the filter condition returns **`False`**, then it updates the row with the value specified in **`other`** parameter.
* If the filter condition returns **`True`**, then it does not update the row.

In the below example, we want to replace the student marks with ‘0’ where marks are less than 80. We pass a filter condition **`df['Marks'] > 80`** to the function.

In [17]:
import pandas as pd

# Create DataFrame from dict
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}

student_df = pd.DataFrame(student_dict)
print(student_df)

# Define filter condition
filt = student_df['Marks'] > 80

student_df['Marks'].where(filt, other=0, inplace=True)
print("\nUpdated dataframe:\n", student_df)

    Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54

Updated dataframe:
     Name  Age  Marks
0    Joe   20  85.10
1    Nat   21   0.00
2  Harry   19  91.54


## DataFrame rename columns

While working with a DataFrame, we may need to **[rename the column](https://github.com/milaan9/10_Python_Pandas_Module/blob/main/001_Python_Pandas_Methods/007_Python_Pandas_DataFrame_rename_columns.ipynb)** or row index. We can use **`DataFrame.rename()`** function to alter the row or column labels.

In the below example, we rename column '**Marks**' to '**Percentage**' in the student DataFrame.

In [18]:
import pandas as pd

# Create DataFrame from dict
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}

student_df = pd.DataFrame(student_dict)
print(student_df)

# rename column
student_df = student_df.rename(columns={'Marks': 'Percentage'})
print("\nUpdated dataframe:\n", student_df)

    Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54

Updated dataframe:
     Name  Age  Percentage
0    Joe   20       85.10
1    Nat   21       77.80
2  Harry   19       91.54


## DataFrame Join

In most of the use cases of Data Analytics, data is gathered from multiple sources, and we need to combine that data for further analysis. In such instances, join and merge operations are required.

**`DataFrame.join()`** function is used to join one DataFrame with another DataFrame as **`df1.join(df2)`**


<div class="alert alert-info"><h4>15.</h4><p>In a new code cell define the following DataFrames:</p></div>

```python
student_dict = {'Name': ['Joe', 'Nat'], 'Age': [20, 21]}
student_df = pd.DataFrame(student_dict)
print(student_df)

marks_dict = {'Marks': [85.10, 77.80]}
marks_df = pd.DataFrame(marks_dict)
print(marks_df)
```

<div class="alert alert-info"><h4>16.</h4><p>Join the two using the code below and display the final result.</p></div>

```python
joined_df = student_df.join(marks_df)
```

## DataFrame GroupBy

**`DataFrame.groupby()`** function groups the DataFrame row-wise or column-wise based on the condition.

If we want to analyze each class’s average marks, we need to combine the student data based on the ‘Grade’ column and calculate its average using **`df.groupby(col_label).mean()`** as shown in the below example.

In [19]:
import pandas as pd

# Create DataFrame from dict
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Grade': ['A', 'B', 'A'], 'Marks': [85.10, 77.80, 91.54]}
student_df = pd.DataFrame(student_dict)
print(student_df)

# apply group by 
student_df = student_df.groupby('Grade').mean(numeric_only=True)
print(student_df)

    Name Grade  Marks
0    Joe     A  85.10
1    Nat     B  77.80
2  Harry     A  91.54
       Marks
Grade       
A      88.32
B      77.80


## DataFrame Sorting

The **`DataFrame.sort_values()`** function is used to sort the DataFrame using one or more columns in ascending (default) or descending order.

<div class="alert alert-info"><h4>16.</h4><p>In a new code cell, define a student_df:</p></div>

```python
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Grade': ['A', 'B', 'A'], 'Marks': [85.10, 77.80, 91.54]}
student_df = pd.DataFrame(student_dict)
print(student_df)
```

<div class="alert alert-info"><h4>17.</h4><p>Sort this DataFrame by Marks:</p></div>


```python
# Resort by Marks
student_df = student_df.sort_values(by=['Marks'], ascending=False)
print(student_df)
```

## DataFrame conversion

It may be necessary to convert the DataFrame back to its original formats like CSV file or a **`dict`**.

Pandas have provided plenty of functions to convert the DataFrames into many different formats.

For example, **`DataFrame.to_dict()`** function is used to convert a **[DataFrame into a dictionary](https://github.com/milaan9/10_Python_Pandas_Module/blob/main/001_Python_Pandas_Methods/008_Python_Pandas_DataFrame_to_Python_dictionary.ipynb)** object.

Below is the example of a DataFrame which we need to convert into the Python **`dict`**.

<div class="alert alert-info"><h4>18.</h4><p>Convert your DataFrame into a dictionary:</p></div>

```python
# convert dataframe to dict
student_dict = student_df.to_dict()
print(student_dict)
```

# Summary

There are loads of functions in Pandas. Here is a list of some that may be useful:

## Create Test Objects

| Operator | Description |
|:---- |:---- |
| **`pd.DataFrame(np.random.rand(20,5))`** | **5 columns and 20 rows of random floats** | 
| **`pd.Series(my_list)`** | **Create a series from an iterable my_list** | 
| **`df.index = pd.date_range('1900/1/30', periods=df.shape[0])`** | **Add a date index** | 

## Viewing/Inspecting Data

| Operator | Description |
|:---- |:---- |
| **`df.head(n)`** | **First n rows of the DataFrame** | 
| **`df.tail(n)`** | **Last n rows of the DataFrame** | 
| **`df.shape`** | **Number of rows and columns** | 
| **`df.info()`** | **Index, Datatype and Memory information** | 
| **`df.describe()`** | **Summary statistics for numerical columns** | 
| **`s.value_counts(dropna=False)`** | **View unique values and counts** | 
| **`df.apply(pd.Series.value_counts)`** | **Unique values and counts for all columns** | 

## Selection

| Operator | Description |
|:---- |:---- |
| **`df[col]`** | **Returns column with label col as Series** | 
| **`df[[col1, col2]]`** | **Returns columns as a new DataFrame** | 
| **`s.iloc[0]`** | **Selection by position** | 
| **`s.loc['index_one']`** | **Selection by index** | 
| **`df.iloc[0,:]`** | **First row** | 
| **`df.iloc[0,0]`** | **First element of first column** | 

## Data Cleaning

| Operator | Description |
|:---- |:---- |
| **`df.columns = ['a','b','c']`** | **Rename columns** | 
| **`pd.isnull()`** | **Checks for null Values, Returns Boolean Arrray** | 
| **`pd.notnull()`** | **Opposite of pd.isnull()** | 
| **`df.dropna()`** | **Drop all rows that contain null values** | 
| **`df.dropna(axis=1)`** | **Drop all columns that contain null values** | 
| **`df.dropna(axis=1,thresh=n)`** | **Drop all rows have have less than n non null values** | 
| **`df.fillna(x)`** | **Replace all null values with x** | 
| **`s.fillna(s.mean())`** | **Replace all null values with the mean** | 
| **`s.astype(float)`** | **Convert the datatype of the series to float** | 
| **`s.replace(1,'one')`** | **Replace all values equal to 1 with 'one'** | 
| **`s.replace([2,3],['two', 'three'])`** | **Replace all 2 with 'two' and 3 with 'three'** | 
| **`df.rename(columns=lambda x: x + 1)`** | **Mass renaming of columns** | 
| **`df.rename(columns={'old_name': 'new_ name'})`** | **Selective renaming** | 
| **`df.set_index('column_one')`** | **Change the index** | 
| **`df.rename(index=lambda x: x + 1)`** | **Mass renaming of index** | 

## Filter, Sort, and Groupby

| Operator | Description |
|:---- |:---- |
| **`df[df[col] > 0.6]`** | **Rows where the column col is greater than 0.6** | 
| **`df[(df[col] > 0.6) & (df[col] < 0.8)]`** | **Rows where 0.8 > col > 0.6** | 
| **`df.sort_values(col1)`** | **Sort values by col1 in ascending order** | 
| **`df.sort_values(col2,ascending=False)`** | **Sort values by col2 in descending order.5** | 
| **`df.sort_values([col1,col2],ascending=[True,False])`** | **Sort values by col1 in ascending order then col2 in descending order** | 
| **`df.groupby(col)`** | **Returns a groupby object for values from one column** | 
| **`df.groupby([col1,col2])`** | **Returns groupby object for values from multiple columns** | 
| **`df.groupby(col1)[col2]`** | **Returns the mean of the values in col2, grouped by the values in col1** | 
| **`df.pivot_table(index=col1,values=[col2,col3],aggfunc=mean)`** | **Create a pivot table that groups by col1 and calculates the mean of col2 and col3** | 
| **`df.groupby(col1).agg(np.mean)`** | **Find the average across all columns for every unique col1 group** | 
| **`df.apply(np.mean)`** | **Apply the function np.mean() across each column** | 
| **`nf.apply(np.max,axis=1)`** | **Apply the function np.max() across each row** | 

## Join/Combine

| Operator | Description |
|:---- |:---- |
| **`df1.append(df2)`** | **Add the rows in df1 to the end of df2 (columns should be identical)** | 
| **`pd.concat([df1, df2],axis=1)`** | **Add the columns in df1 to the end of df2 (rows should be identical)** | 
| **`df1.join(df2,on=col1, how='inner')`** | **SQL-style join the columns in df1 with the columns on df2 where the rows for col have identical values. The 'how' can be 'left', 'right', 'outer' or 'inner'** | 

## Statistics

| Operator | Description |
|:---- |:---- |
| **`df.describe()`** | **Summary statistics for numerical columns** | 
| **`df.mean()`** | **Returns the mean of all columns** | 
| **`df.corr()`** | **Returns the correlation between columns in a DataFrame** | 
| **`df.count()`** | **Returns the number of non-null values in each DataFrame column** | 
| **`df.max()`** | **Returns the highest value in each column** | 
| **`df.min()`** | **Returns the lowest value in each column** | 
| **`df.median()`** | **Returns the median of each column** | 
| **`df.std()`** | **Returns the standard deviation of each column** |

## Importing Data

| Operator | Description |
|:---- |:---- |
| **`pd.read_csv(filename)`** | **From a CSV file** | 
| **`pd.read_table(filename)`** | **From a delimited text file (like TSV)** | 
| **`pd.read_excel(filename)`** | **From an Excel file** | 
| **`pd.read_sql(query, connection_object)`** | **Read from a SQL table/database** | 
| **`pd.read_json(json_string)`** | **Read from a JSON formatted string, URL or file.** | 
| **`pd.read_html(url)`** | **Parses an html URL, string or file and extracts tables to a list of dataframes** | 
| **`pd.read_clipboard()`** | **Takes the contents of your clipboard and passes it to read_table()** | 
| **`pd.DataFrame(dict)`** | **From a dict, keys for columns names, values for data as lists** |

## Exporting Data

| Operator | Description |
|:---- |:---- |
| **`df.to_csv(filename)`** | **Write to a CSV file** | 
| **`df.to_excel(filename)`** | **Write to an Excel file** | 
| **`df.to_sql(table_name, connection_object)`** | **Write to a SQL table** | 
| **`df.to_json(filename)`** | **Write to a file in JSON format** |

## Challenge

**1. Download `Challenge_32.ipynb` from Teams.**

**2. Upload this file into your own *Project* on Deepnote by dragging the `Challenge_32.ipynb` file onto the Notebooks tab on the left-hand side.** 

**3. Use this notebook to complete Challenge 32 in Deepnote.**